@extends('adminlte::page')

@section('title', 'Permisos')

@section('content_header')
    <div class="d-flex justify-content-between">
        <h1>Permisos</h1>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newPermisosModal"><i class="fa fa-plus"
                aria-hidden="true"></i> Permiso</button>
    </div>
@stop

@section('content')
    <div id="loading" style="display: none;" class="justify-content-center align-self-center">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="200"
            height="200" style="shape-rendering: auto; display: block; background: rgb(255, 255, 255);"
            xmlns:xlink="http://www.w3.org/1999/xlink">
            <g>
                <circle stroke-width="8" stroke="#f5a9b8" fill="none" r="0" cy="50" cx="50">
                    <animate begin="0s" calcMode="spline" keySplines="0 0.2 0.8 1" keyTimes="0;1" values="0;57"
                        dur="1.5625s" repeatCount="indefinite" attributeName="r"></animate>
                    <animate begin="0s" calcMode="spline" keySplines="0.2 0 0.8 1" keyTimes="0;1" values="1;0"
                        dur="1.5625s" repeatCount="indefinite" attributeName="opacity"></animate>
                </circle>
                <circle stroke-width="8" stroke="#5bcefa" fill="none" r="0" cy="50" cx="50">
                    <animate begin="-0.78125s" calcMode="spline" keySplines="0 0.2 0.8 1" keyTimes="0;1" values="0;57"
                        dur="1.5625s" repeatCount="indefinite" attributeName="r"></animate>
                    <animate begin="-0.78125s" calcMode="spline" keySplines="0.2 0 0.8 1" keyTimes="0;1" values="1;0"
                        dur="1.5625s" repeatCount="indefinite" attributeName="opacity"></animate>
                </circle>
                <g></g>
            </g><!-- [ldio] generated by https://loading.io -->
        </svg>
    </div>

    <div id="content">
        <div class="card">
            <div class="card-body">
                @if (session('success') == 'Permiso guardado')
                    <x-adminlte-alert theme="success" title="Éxito" id="success-alert">
                        Permiso guardado correctamente.
                    </x-adminlte-alert>
                @elseif (session('success') == 'Permiso eliminado')
                    <x-adminlte-alert theme="success" title="Éxito" id="success-alert">
                        Permiso eliminado correctamente.
                    </x-adminlte-alert>
                @elseif (session('success') == 'Permiso actualizado')
                    <x-adminlte-alert theme="success" title="Éxito" id="success-alert">
                        Permiso actualizado correctamente.
                    </x-adminlte-alert>
                @elseif (session('error'))
                    <x-adminlte-alert theme="danger" title="Error" id="error-alert">
                        Error al guardar el Permiso.
                    </x-adminlte-alert>
                @endif

                @php
                    $heads = ['ID', 'Nombre', ['label' => 'Actions', 'no-export' => true, 'width' => 15]];

                    $btnEdit = '';
                    $btnDelete = '<button type="submit" class="btn btn-xs btn-default text-danger mx-1 shadow" title="Delete">
                                    <i class="fa fa-lg fa-fw fa-trash"></i>
                                </button>';

                    $config = [
                        'language' => [
                            'url' => '/js/lang/es-ES.json',
                        ],
                    ];
                @endphp

                <x-adminlte-datatable id="table1" :heads="$heads" :config="$config">
                    @foreach ($permisos as $permiso)
                        <tr>
                            <td>{{ $permiso->id }}</td>
                            <td>{{ $permiso->name }}</td>
                            <td>
                                <button class="btn btn-xs btn-default text-primary mx-1 shadow edit-button"
                                    data-id="{{ $permiso->id }}" title="Edit">
                                    <i class="fa fa-lg fa-fw fa-pen"></i>
                                </button>

                                <form style="display: inline" action="{{ route('permisos.destroy', $permiso->id) }}"
                                    method="post" class="formEliminar">
                                    @csrf
                                    @method('DELETE')
                                    {!! $btnDelete !!}
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </x-adminlte-datatable>

            </div>
        </div>

        <div class="modal fade" id="newPermisosModal" tabindex="-1" role="dialog" aria-labelledby="newPermisosModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="newPermisosModalLabel">Nuevo Permisos</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div id="form-loading" style="display: none;" class="justify-content-center align-self-center">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid"
                                width="200" height="200"
                                style="shape-rendering: auto; display: block; background: rgb(255, 255, 255);"
                                xmlns:xlink="http://www.w3.org/1999/xlink">
                                <g>
                                    <circle stroke-width="8" stroke="#f5a9b8" fill="none" r="0" cy="50"
                                        cx="50">
                                        <animate begin="0s" calcMode="spline" keySplines="0 0.2 0.8 1"
                                            keyTimes="0;1" values="0;57" dur="1.5625s" repeatCount="indefinite"
                                            attributeName="r"></animate>
                                        <animate begin="0s" calcMode="spline" keySplines="0.2 0 0.8 1"
                                            keyTimes="0;1" values="1;0" dur="1.5625s" repeatCount="indefinite"
                                            attributeName="opacity"></animate>
                                    </circle>
                                    <circle stroke-width="8" stroke="#5bcefa" fill="none" r="0" cy="50"
                                        cx="50">
                                        <animate begin="-0.78125s" calcMode="spline" keySplines="0 0.2 0.8 1"
                                            keyTimes="0;1" values="0;57" dur="1.5625s" repeatCount="indefinite"
                                            attributeName="r"></animate>
                                        <animate begin="-0.78125s" calcMode="spline" keySplines="0.2 0 0.8 1"
                                            keyTimes="0;1" values="1;0" dur="1.5625s" repeatCount="indefinite"
                                            attributeName="opacity"></animate>
                                    </circle>
                                    <g></g>
                                </g><!-- [ldio] generated by https://loading.io -->
                            </svg>
                        </div>
                        <div id="form-content">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form id="permisoForm" action="{{ route('permisos.store') }}" method="post">
                                @csrf
                                <x-adminlte-input type="text" name="nombre" label="Nombre"
                                    placeholder="nuevo permiso" label-class="text-lightblue" value="{{ old('nombre') }}">
                                    <x-slot name="prependSlot">
                                        <div class="input-group-text">
                                            <i class="fas fa-cube text-lightblue"></i>
                                        </div>
                                    </x-slot>
                                </x-adminlte-input>
                                <div class="modal-footer">
                                    <x-adminlte-button label="Cerrar" theme="secondary" icon="fas fa-times"
                                        data-dismiss="modal" />
                                    <x-adminlte-button type="submit" label="Guardar" theme="primary"
                                        icon="fas fa-save" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')
    {{-- Add here extra stylesheets --}}
@stop

@section('js')
    <script>
        $(document).ready(function() {
            $('#loading').css('display', 'flex');
            $('#content').hide();
            $(window).on('load', function() {
                $('#loading').hide();
                $('#content').show();
            });

            @if ($errors->any())
                $('#newPermisosModal').modal('show');
            @endif

            // Hide alerts after 5 seconds
            setTimeout(function() {
                $('#success-alert').fadeOut('slow');
                $('#error-alert').fadeOut('slow');
            }, 5000);

            $('.formEliminar').submit(function(e) {
                e.preventDefault();
                Swal.fire({
                    title: '¿Estás seguro?',
                    text: "¡No podrás revertir esto!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: '¡Sí, bórralo!',
                    cancelButtonText: 'Cancelar'
                }).then((result) => {
                    if (result.isConfirmed) {
                        this.submit();
                        $('#loading').css('display', 'flex');
                        $('#content').hide();
                    } else {
                        $('#loading').hide();
                        $('#content').show();
                    }
                });
            });

            $('#permisoForm').submit(function() {
                $('#form-loading').css('display', 'flex');
                $('#form-content').hide();
            });

            $('.edit-button').click(function() {
                var id = $(this).data('id');
                $('#form-loading').css('display', 'flex');
                $('#form-content').hide();
                $.ajax({
                    url: '/permisos/' + id + '/edit',
                    method: 'GET',
                    success: function(data) {
                        $('#form-loading').hide();
                        $('#form-content').show();
                        $('#newPermisosModalLabel').text('Editar Permiso');
                        $('#permisoForm').attr('action', '/permisos/' + id);
                        $('#permisoForm').append('@method('PUT')');
                        $('input[name="nombre"]').val(data.name);
                        $('#newPermisosModal').modal('show');
                    }
                });
            });
        });
    </script>

    @if ($errors->any())
        <script>
            $(document).ready(function() {
                console.log("Hola");
                $('#newPermisosModal').modal('show');
            });
        </script>
    @endif
@stop
